spring:
  application:
    name: Secure-Library-Management-System-API

  datasource:
    url: jdbc:h2:mem:inventorydb;
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  mvc:
    problemdetails:
      enabled: true

application:
    # Jwt Configuration
  jwt:
    config:
      encryption-key: 5heUCJxsTsaYyTE6+XB+tnpvdZkttNv5PBWHe9v9q73kGjDa2+UI2YQMWPj1Fpec
        # Expiration in milliseconds
      token-expiration: 600000 # 10 minutes

logging:
  level:
    com.SLMS: INFO

